### ISSUE TITLE
Transport has duplicate UIM members

### ISSUE THREAD

**Issue by wimjongman** [i-ntERPrise/intERPrise#27]
In Transport_Services/SRCUIM there are three duplicate files. They also have differences. Can someone please figure out which of the three are correct and remove the others?

IRPTCFG.MENU
IRPTCFG.MNU

IRPTMAIN.MENU
IRPTMAIN.MNU

IRPTOPS.MENU
IRPTOPS.MNU

**Comment by wimjongman** [comment]
As an intermediate action I renamed the menus ending with the MNU. The system now compiles fine but this should be looked at.

**Comment by jerps** [comment]
Ok

**Comment by ChrisHird** [comment]
Yes the renames occurred in error (not sure where?) but I have already corrected on my master copy which will be pushed up once I have some new updates ready.

**Comment by wimjongman** [comment]
I don't want to be the git police but we should not mix in changes. Please revert your renames (right click on the sources and say Team/replace with/HEAD revision) and let's do this in a separate isolated change.

**Comment by wimjongman** [comment]
If you push yes. But you will be pushing with other changes which makes the process fuzzy.

An issue should only described one problem and the push should only contain these changes.

**Comment by wimjongman** [comment]
Chris, did you rename them earlier?

**Comment by wimjongman** [comment]
Sorry I was confused. Ignore my previous comments. I was thinking we were discussing the copybook renames.

**Comment by ChrisHird** [comment]
Duplicate objects have been deleted.
