### ISSUE TITLE
Project naming conventions

### ISSUE THREAD

**Issue by wimjongman** [i-ntERPrise/intERPrise#29]
It seems that there are currently three distinct projects in this repository. They are called Database_Services, UI_Services and Transport_Services. 

I propose to follow the reverse dns naming convention [1] and rename these projects to:

org.i-nterprise.db.services
org.i-nterprise.transport.services
org.i-nterprise.ui.services
    php.easycom

[1] https://en.wikipedia.org/wiki/Reverse_domain_name_notation

**Comment by ChrisHird** [comment]
As already suggested I agree with the new naming convention. lets put into place. Once done we call all re-pull the repository to get the updated names. Need to also amend the IBM i Project properties as they are reflective of the current directory structure.

**Comment by wimjongman** [comment]
I also fixed the .project properties. The .IBMi directory must never be pushed because it contains local changes.
