### ISSUE TITLE
Missing copy member exist with a 035 prefix

### ISSUE THREAD

**Issue by wimjongman** [i-ntERPrise/intERPrise#32]
When trying to compile the database services it complains about missing copy members. The copy members are there but with a 035 suffix. When the suffix is removed all compiles fine,

**Comment by ChrisHird** [comment]
The content of the Repository is a beta copy, we have always said that the entire content could be replaced in a future commit. The content is meant to show the structure and technology only in an attempt to get feedback from the community. Once we have the documented conventions etc we will be add more content based on the documented conventions.

**Comment by wimjongman** [comment]
I'm not sure if I understand this. The repository is a stub?

**Comment by wimjongman** [comment]
Can I get a go for https://github.com/i-ntERPrise/intERPrise/pull/33

**Comment by ChrisHird** [comment]
Yes
